name: Report Bug
description: Report something that's unexpected or not working correctly.
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Details
      description: "Describe the issue in detail, and steps to reproduce it."
      placeholder: "MateEngine crashed when I clicked on VRM/ME button..."
    validations:
      required: true

  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies
      description: Confirm you've set up your Linux environment correctly.
      options:
        - label: I already installed all of the libraries listed out in README.md, including `libayatana-appindicator3-1`
        - label: I launch MateEngine with `launch.sh` script
        - label: I already enabled composition in compositor / window manager settings
        - label: I am not using tiling window managers like i3 or Hyprland
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: "-nolog output"
      description: Terminal output when launching MateEngine with argument `-nolog`
      placeholder: |
        ```
        Place the output here...
        ```
    validations:
      required: true

  - type: textarea
    id: system-information
    attributes:
      label: System Information
      description: "Your Linux Information."
      placeholder: |
        OS and version:
        Kernel version:
        Desktop environment:
    validations:
      required: true

  - type: dropdown
    id: wm
    attributes:
      label: X11 or Wayland
      description: Is your window manager based on X11 or Wayland?
      options:
        - "X11"
        - "Wayland"
    validations:
      required: true

  - type: checkboxes
    id: arch_btw
    attributes:
      label: Confirmation
      options:
        - label: I use Arch btw
    validations:
      required: false
