name: Feature Request
description: Suggest a new idea or enhancement.
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Describe your idea
      description: |
        What would you like to see added or changed?

        ⚠️ Please submit only **one** feature per request. Submitting multiple features will make the request invalid and it may be ignored or closed.
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: true

  - type: input
    id: benefit
    attributes:
      label: Why is this useful?
    validations:
      required: true

  - type: checkboxes
    id: read_note
    attributes:
      label: Confirmation
      description: Confirm you are not a bot.
      options:
        - label: I confirm this request includes **only one** feature.
    validations:
      required: true
