name: Improvement Needed
description: Suggest what to implement or enhance on specific Linux environments.
title: "[ENHANCEMENT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Describe your idea
      description: |
        What would you like to see improved or enhanced?

        ⚠️ Please only suggest environment-related what to improve. Adding new features of this MateEngine port (e.g. editing VRM stuff) is currently not on the roadmap, and suggesting new features will likely result in issue closing/locking.
      placeholder: "I'm always frustrated when MateEngine works buggy under Wayland DEs..."
    validations:
      required: true

  - type: input
    id: benefit
    attributes:
      label: Expected behaviour
    validations:
      required: true

  - type: checkboxes
    id: read_note
    attributes:
      label: Confirmation
      description: Confirm you are not a bot.
      options:
        - label: I confirm this is **not a feature request**.
    validations:
      required: true
